// Copyright 2022 ClavinJune/bjora
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=Environment -trimprefix=Environment"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnvironmentUndefined-0]
	_ = x[EnvironmentTest-1]
	_ = x[EnvironmentDev-2]
	_ = x[EnvironmentStg-3]
	_ = x[EnvironmentProd-4]
}

const _Environment_name = "UndefinedTestDevStgProd"

var _Environment_index = [...]uint8{0, 9, 13, 16, 19, 23}

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_Environment_index)-1) {
		return "Environment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
